### ISSUE TITLE
chromeArgs Ignored When browserContext set to 'incognito'

### ISSUE THREAD

**Issue by Marcus-Allen1** [argos-ci/jest-puppeteer#231]
## 🐛 Bug Report

When you have the `browserContext` set to `incognito` in your `jest-puppeteer.config.js` this causes any other arguments you have set (bar headless) to be ignored.
In my example I needed to force puppeteer to launch with the locale `en-GB` which works fine with `browserContext: 'default'` but when I changed it to `browserContext: 'incognito'` then the `lang` flag was ignored and defaulted back to `en-US`

## To Reproduce

- Have a `lang` affected input (ie Date)
- Create a `jest-puppeteer.config.js` in the format:
```
module.exports = {
    launch: {
        dumpio: true,
        headless: true/false,
        args: ['--lang=en-GB']
    },
    browserContext: 'default/incognito',
}
```
- Run and see if date is output in `en-GB` format `DD-MM-YYYY` or `en-US` format `MM-DD-YYYY`

## Expected behavior

I expected any chromeArgs that were passed through via config to still be honoured while running in `incognito` mode

```bash
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 77.09 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
 - npm: 6.9.0 - ~/Documents/Sampling2/sampling-member-app/node_modules/.bin/npm
## npmPackages:
 - jest-puppeteer: ^4.1.0 => 4.1.0
```

**Comment by gregberge** [comment]
Please upgrade to v8 and reopen submit a new issue if you experience this problem.
