### ISSUE TITLE
jest-dev-server can't detect used ports since 4.1.1

### ISSUE THREAD

**Issue by Dilatorily** [argos-ci/jest-puppeteer#233]
## 💥 Regression Report

Since the latest release (4.1.1), `jest-puppeteer` will timeout when trying to detect if a port is used. I was able to narrow it down to the changes in `jest-dev-server` introduced in #227.

## Last working version

Worked up to version: `jest-dev-server@4.0.0`

Stopped working in version: `jest-dev-server@4.1.1`

## To Reproduce

1. Start an `express` server on port `3000`
2. Set the `server.port` to `3000` in the `jest-puppeteer.config.js` file
3. `jest`

## Expected behavior

`jest-puppeteer` should be able to detect if the port is used, and the tests should pass.

## Link to repl or repo (highly encouraged)
https://github.com/Dilatorily/jest-puppeteer-issue

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS Sierra 10.12.6
 - CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
 - Memory: 2.71 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 11.14.0 - /usr/local/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - jest-puppeteer: ^4.1.1 => 4.1.1
```

**Comment by neoziro** [comment]
@xiaoyuhen any infos on this?

**Comment by sync** [comment]
Perhaps this is what is causing the issue: https://github.com/smooth-code/jest-puppeteer/commit/59d796b59c213b53c8842f2545fbaabf09d09dd4

**Comment by xiaoyuhen** [comment]
@sync 

yeah, its a bug from this https://github.com/smooth-code/jest-puppeteer/commit/59d796b59c213b53c8842f2545fbaabf09d09dd4 commit.

I am working hard to fix it

**Comment by sync** [comment]
Don’t work too hard. Take the time and don’t stress ❤️

**Comment by xiaoyuhen** [comment]
`wait-on` is very strange.


this code can work well
```
try {
  await waitOn(opts);
} catch (err) {
  throw new JestDevServerError(
    `Server has taken more than ${launchTimeout}ms to start.`,
    ERROR_TIMEOUT,
  )
}
```

this code cannot work

```
let timeout
await Promise.race([
    new Promise((resolve, reject) => {
      timeout = setTimeout(
        () =>
          reject(
            new JestDevServerError(
              `Server has taken more than ${launchTimeout}ms to start.`,
              ERROR_TIMEOUT,
            ),
          ),
        launchTimeout,
      )
    }),
    waitOn(opts),
  ])
  clearTimeout(timeout)
}
```

**Comment by xiaoyuhen** [comment]
it seems like we must set `tcp` prefixes, then `wait-on` package can find our server.

very sorry about the problem, it will fix on this https://github.com/smooth-code/jest-puppeteer/pull/235 PR.  cc @sync  @Dilatorily

**Comment by flo-sch** [comment]
Hej @xiaoyuhen, I have some issues with a local express instance using https.createServer ;
(The server itself starts but jest always show the timeout message `Server has taken more than {whichever timeout duration I set up in jest-puppeteer.config.js} to start.`)
(HTTP mode without certificates works fine)

As a side effect, the teardown is not invoked, and the local process continues to run after timeout.

Just wondering if this is related to this issue as well, and if #235 has been released already // is planned to be released?

(Nothing urgent on my side, just wish to know)

**Comment by domoritz** [comment]
Hi @xiaoyuhen. In https://github.com/smooth-code/jest-puppeteer/issues/236#issuecomment-489136131, you mentioned that a patch is on its way. When do you plan to publish a fix for jest-puppeteer?

**Comment by gregberge** [comment]
Hi should be fixed in v8, please upgrade and reopen this issue if you experience the problem.
