### ISSUE TITLE
Permission denied when starting dev-server 

### ISSUE THREAD

**Issue by davidrv87** [argos-ci/jest-puppeteer#267]
## 💥 Regression Report

I have been using dev-server for a while to start the server before running my tests without having to run them as `sudo`. After the upgrade to 4.3.0, the code will throw and `undefined` error. 

I say `undefined` because there is a Promise rejection without error (see [this line](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-dev-server/src/global.js#L100)). 

The code above is called [here](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/global.js#L27). Although, that line of code in my `node_modules/jest-environment-puppeteer/global.js` is 

```javascript
try {
    await (0, _jestDevServer.setup)(config.server);
} catch (error) {
    if (error.code === _jestDevServer.ERROR_TIMEOUT) {
[...]
```

This is the stacktrace:
```bash
TypeError: Cannot read property 'code' of undefined
    at setup (/Users/david/Projects/cards-preflight-service/node_modules/jest-environment-puppeteer/lib/global.js:35:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I manually edit [this line](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-dev-server/src/global.js#L100) to reject with the `error` then the stacktrace looks like this:

```bash
Error: listen EACCES: permission denied 127.0.0.1:80
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
```

## Last working version

Worked up to version: 4.2.0

Stopped working in version: 4.3.0

## To Reproduce

My `jest-puppeteer.config.js` has always looked like this:

```javascript
module.exports = {
  server: {
    command: 'node test/fixtures/dummy_frontend/serv.js',
    port: 80
  },
  launch: {
    dumpio: false,
    headless: process.env.HEADLESS !== 'false',
    args: ['--no-sandbox', '--disable-setuid-sandbox']'
  },
  browserContext: 'incognito'
};
```

## Expected behavior

The dev-server starts as it used to start on port 80, test run and the dev-server is killed at the end.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.14.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 571.46 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
## npmPackages:
 - jest-dev-server: 4.3.0 => 4.3.0 
 - jest-environment-puppeteer: 4.3.0 => 4.3.0 
 - jest-puppeteer: 4.3.0 => 4.3.0 
```

**Comment by neoziro** [comment]
Hello @davidrv87, could you try to submit a PR to fix it?

**Comment by davidrv87** [comment]
To be quite honest, I don't know the fix for this. I can only point you to the lines where the issue is found. At the very most, I could submit the PR to address the issue of the rejected promise without error but it is basically changing [this line](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-dev-server/src/global.js#L100)

From:

```javascript
err.code === 'EADDRINUSE' ? resolve(cleanupAndReturn(true)) : reject(),
```

to:

```javascript
err.code === 'EADDRINUSE' ? resolve(cleanupAndReturn(true)) : reject(err),
```

**Comment by neoziro** [comment]
@davidrv87 OK let's do it for now.

**Comment by abrcdf1023** [comment]
This bug can be fixed by this.

```javascript
server: {
  command: 'node server.js',
},
```

And it only appear when set port at 80.

```javascript
server: {
  command: 'node server.js',
  port: '80'
},
```

**Comment by gregberge** [comment]
Using port 80 is not a good idea. If you have to do it, then start jest with a user that has the required permission to start a server on this port.
