### ISSUE TITLE
jestPuppeteer.resetBrowser() does not clear down service workers

### ISSUE THREAD

**Issue by benjaminkay93** [argos-ci/jest-puppeteer#280]
## 🐛 Bug Report

`jestPuppeteer.resetBrowser()` does not seem to destroy any running service workers. 

## To Reproduce

1. Setup a file to 
```
beforeEach(async () => {
  await jestPuppeteer.resetPage();
  await jestPuppeteer.resetBrowser();
});
```
2. Install a service worker in one test.
3. In another test, using page.evaluate you can assert a service worker has been installed.

## Expected behavior

I would expect `resetBrowser` to destroy all running and active service workers.

## Link to repl or repo (highly encouraged)

If this is needed to add more context, I can do this. It feels more feature request now i think about it than bug 😄 

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
 - Memory: 286.91 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
 - Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.0/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
```

**Comment by gregberge** [comment]
Don't know if it is still relevant or not, I close it feel free to open a new issue.
