### ISSUE TITLE
Default settings for visible is not working properly for toClick expect

### ISSUE THREAD

**Issue by GuskiS** [argos-ci/jest-puppeteer#285]
## 🐛 Bug Report

If I do `setDefaultOptions({ visible: true, timeout: 5000 });` visible is set for default options, but not being used for:
https://github.com/smooth-code/jest-puppeteer/blob/09703eaeeeab553e13142153b55030db05611f7c/packages/expect-puppeteer/src/matchers/toMatchElement.js#L7-L9

if I call:
https://github.com/smooth-code/jest-puppeteer/blob/09703eaeeeab553e13142153b55030db05611f7c/packages/expect-puppeteer/src/matchers/toClick.js#L3-L6

## Expected behavior

Default visible should be used when called `.toClick`

**Comment by gregberge** [comment]
Please upgrade to v8 and reopen submit a new issue if you experience this problem.
