### ISSUE TITLE
Web components

### ISSUE THREAD

**Issue by dmnrmr** [argos-ci/jest-puppeteer#296]
## 🚀 Feature Proposal

Matching elements inside web components.

## Motivation

Current way of matching elements (using `querySelectorAll` does not find any elements that are placed inside a web component. I.e. puppeteer's `waitForSelector` method works fine.

## Example

Example in [related article](https://medium.com/@kevinsimper/document-queryselector-with-web-components-76a8be5bc59)

## Pitch

As a user it makes perfect sense to me to use `toMatchElement` and to expect an element to be found.

**Comment by gregberge** [comment]
We will not go in this direction. `expect-puppeteer` will probably be deprecated in favor of [pptr-testing library](https://testing-library.com/docs/pptr-testing-library/intro/).
