### ISSUE TITLE
Server not stopped when jest --watch exits

### ISSUE THREAD

**Issue by Volcomix** [argos-ci/jest-puppeteer#305]
## 🐛 Bug Report

When exiting `jest --watch` (by pressing `q`), the server doesn't seem to stop.

## To Reproduce

```js
// jest-puppeteer.config.js
module.exports = {
  server: {
    command: 'python -m http.server 8081 --directory src',
    port: 8081,
  },
}
```

1. `jest --watch` (or `yarn test --watch` in my case)
2. run some tests
3. press `q` to quit
4. `jest --watch` again

```
Determining test suites to run...
✔ Another process is listening on 8081. Should I kill it for you? On linux, this may require you to enter your password. … yes

  ● Test suite failed to run

    TypeError: Cannot read property 'name' of undefined

      at logProcDetection (node_modules/jest-dev-server/lib/global.js:70:69)
      at ask (node_modules/jest-dev-server/lib/global.js:153:9)
      at async setupJestServer (node_modules/jest-dev-server/lib/global.js:174:7)
          at async Promise.all (index 0)
      at async setup (node_modules/jest-dev-server/lib/global.js:123:3)
      at async setup (node_modules/jest-environment-puppeteer/lib/global.js:38:7)
```

## Expected behavior

In step 4. I would expect to have the tests running again without any confirmation to kill a running process.

## Link to repl or repo

https://github.com/Volcomix/waane/tree/e4c3631a7424c8fd1cd67f858990de95eb369556

## Environment

```bash
## System:
 - OS: Linux 5.4 Arch Linux
 - CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
 - Memory: 9.14 GB / 15.59 GB
 - Container: Yes
 - Shell: 5.0.11 - /bin/bash
## Binaries:
 - Node: 13.5.0 - /usr/bin/node
 - Yarn: 1.21.1 - /usr/bin/yarn
 - npm: 6.13.4 - /usr/bin/npm
 - Watchman: 4.9.0 - /usr/bin/watchman
## npmPackages:
 - jest-puppeteer: ^4.4.0 => 4.4.0
```

**Comment by Volcomix** [comment]
Seems to be related to `find-process` module because:
```bash
$ npx find-process 32431
Found 1 process

[python]
pid: 32431
cmd: python -m http.server 8081 --directory src
```
but
```bash
$ npx find-process -p 8081
No process found
```

**Comment by Volcomix** [comment]
Issue opened in `find-process` repo: https://github.com/yibn2008/find-process/issues/31

**Comment by rjdestigter** [comment]
I think I might be having the same issue. When my test fails the node server isn't shut down and I have to manually kill it before running the tests again.

**Comment by wheresrhys** [comment]
Workaround using https://www.npmjs.com/package/start-server-and-test:

In your config file something like:
```
if (!process.env.NO_SERVER) {
	config.server = {
		command: 'node ./server/start.js',
		port: process.env.PORT || 3456,
	},
};
```
 then run a task like:
```
start-server-and-test "NODE_ENV=test make run" http://localhost:3456 "NO_SERVER=true jest test --watch"
```

**Comment by i-like-robots** [comment]
The `teardown` method is called after each test run, it specifically guards against tearing down the servers when in watch mode:

https://github.com/smooth-code/jest-puppeteer/blob/56715a8938e859d994c9ea1520cf44a3c796c98e/packages/jest-environment-puppeteer/src/global.js#L69-L71

Unfortunately if Jest is idle between test runs when the process is shut down then this teardown method is not called... and I can't yet see any way to hook into Jest to do so.

**Comment by gregberge** [comment]
We can't really stop server when jest is closing. To mitigate this, jest-dev-server detects the server running on the port.
