### ISSUE TITLE
Adding package.json configuration option, or making the jest-puppeteer config path more flexible

### ISSUE THREAD

**Issue by igneel64** [argos-ci/jest-puppeteer#318]
## 🚀 Feature Proposal

How about adding the option to add the configuration parameters directly to package.json as a `"jest-puppeteer"` field ? 

## Motivation

Currently the only place you can add the configuration is in the root of the project with the `jest-puppeteer.config.js` file. This seems a bit unyieldy and could be consider "yet another file" for most people with just 3-4 lines of configuration.
The addition of the package.json config option is something that many other libraries provide e.g. `jest`, `eslint` and others.
Certainly it is not so flexible as a JavaScript file, but could fit many cases.

Another consideration would be to be able to search for the `jest-puppeteer.config.js` recursively from the current file running, and use the first one found. This would make it a bit more "clean" as it would allow people to add the `jest-puppeteer.config.js` file, closer to where it would belong conceptually.

## Note
If this is something wanted, I could begin working on a first implementation 😃

**Comment by StevenWeathers** [comment]
I would like to see this, more and more javascript tools are expecting custom configs in root and it really adds up quick.  I've recently begun trying to move all my tooling configs into a subfolder in effort to clean up the root, and realized this tool doesn't yet support this.

**Comment by igneel64** [comment]
I would do my best to come with a PR in the comming days @StevenWeathers

**Comment by lukasoppermann** [comment]
I would love to see this as well. I am also annoyed bay having yet another config file with 3 options. 😁

**Comment by igneel64** [comment]
@lukasoppermann @StevenWeathers PR is open, if you could check it out it would probably speed up the process a bit 😄

**Comment by lukasoppermann** [comment]
Awesome @igneel64 that is great.

**Comment by yacineblr** [comment]
Do you have any news please ?

**Comment by gregberge** [comment]
We will work on it.

**Comment by gregberge** [comment]
Supported in v8+. Docs also updated.
