### ISSUE TITLE
ability toClick() radioButtons

### ISSUE THREAD

**Issue by abhidp** [argos-ci/jest-puppeteer#320]
## 🚀 Feature Proposal

Please provide the ability to select radioButtons and checkBoxes  via .toClick() function

## Motivation

There is no easy way to target Radio Buttons and Check Boxes based on their values like there is a function to select values from Dropdowns
## Example

something like 
  ```
await expect(page).toClick('radio', { value: 'Yes' });
```

for the element:

```
<input id="taxClient" type="radio" value="Yes">
``` 
![image](https://user-images.githubusercontent.com/30851622/74625967-38ef9a80-51a2-11ea-96f4-9e4aeb6010e9.png)

**Comment by kme211** [comment]
Hi, so I haven't tried this but does `await expect(page).toClick('input[type="radio"][value="Yes"]');` work?

**Comment by f-g-s** [comment]
I use this for radio buttons until the feature is ready:

`        
await page.evaluate(() => { let radio = document.querySelector("#myRadio"); radio.click();
});
`

**Comment by gregberge** [comment]
Using the correct selector it works, so I close this issue.
