### ISSUE TITLE
jest-dev-server timeout does not clean up processes started by 'command'

### ISSUE THREAD

**Issue by thernstig** [argos-ci/jest-puppeteer#341]
## 🐛 Bug Report

Using `jest-dev-server`, set a command like:

```javascript
module.exports = {
  command: 'npm run start',
  launchTimeout: 1000,
}
```

If the timeout occurs, you get this message:

> Server has taken more than 1000ms to start.

The problem here is that `jest-dev-server` then never sends the proper signals to the processes started by the `command`, meaning they get hanging. As a comparison, pressing ´ctrl+c` after the server has started properly cleans up the resources.

## To Reproduce

Add the above config and a very short launchTimeout and notice how the started `command` never stops (check e.g. via the `ps` command).

## Expected behavior

`jest-dev-server` should send the proper signals to launched `command`, even after a `launchTimeout` occured.

**Comment by ryall** [comment]
Also seeing

**Comment by flying-sheep** [comment]
This is extremely annoying, could you please take a look?

**Comment by UziTech** [comment]
PRs are welcome 😁👍

**Comment by gregberge** [comment]
Please upgrade to v8 and reopen submit a new issue if you experience this problem.
