### ISSUE TITLE
Adding toTap to support applications built for touch screen (or for example applications that were built 

### ISSUE THREAD

**Issue by ryanphung** [argos-ci/jest-puppeteer#377]
##  🚀 Feature Proposal

Adding support for touch screen.

## Motivation

For testing of apps built for touch screen, or apps that were built with [react-native-web](https://github.com/necolas/react-native-web).

## Example

```
await expect(page).toTap('button', { text: 'Home' })
```

## Pitch

If we add touch screen support it will make Jest Puppeteer available to a huge community of mobile and tablet web app developers. Surprised that I couldn't find a lot of discussion on this.

I'm happy to start with a PR to add support for `toTap`, as a start.

**Comment by UziTech** [comment]
A PR would be a appreciated. 👌

**Comment by gregberge** [comment]
There is not lot of traction on this issue, also we will move away from expect-puppeteer in favor of other solutions. So I close it.
