### ISSUE TITLE
jest-dev-server requires `ps` to be available as a command, which isn't true in many CI images

### ISSUE THREAD

**Issue by alexrecuenco** [argos-ci/jest-puppeteer#378]
## 🐛 Bug Report

After the tests are run, the teardown throws an error when executing the kill command, (It is using find_process, and find_process requires `ps`)

## To Reproduce

Run the jest-dev-server on a docker container without ps. It will throw an error at teardown and not clean correctly

## Expected behavior

When the teardown occurs, it shouldn't throw an error

## Link to repl or repo (highly encouraged)

I think it isn't needed, it is just a requirements issue that should be maybe documented.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
➜ npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard

## System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 123.71 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v13.14.0/bin/npm
## npmPackages:
 - expect-puppeteer: ^4.4.0 => 4.4.0 
 - jest-puppeteer: ^4.4.0 => 4.4.0 

```

**Comment by gregberge** [comment]
@alexrecuenco it is only checked at setup, using `error` or `ignore` strategy should fix it.
