### ISSUE TITLE
Doesn't support reading in `jest-puppeteer.config.cjs` by default

### ISSUE THREAD

**Issue by cpiber** [argos-ci/jest-puppeteer#444]
## 🐛 Bug Report

`jest-puppeteer` doesn't support ES Module config files; In `type: module` packages it should therefore find `jest-puppeteer.config.cjs` instead.

## To Reproduce

- Create a package and put `"type": "module"` in package.json
- Create `jest-puppeteer.config.cjs` with configuration

## Expected behavior

Reads config from `jest-puppeteer.config.cjs`.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
 - Memory: 3.52 GB / 15.60 GB
 - Container: Yes
 - Shell: 5.8 - /usr/bin/zsh
## Binaries:
 - Node: 15.14.0 - /usr/bin/node
 - Yarn: 1.22.5 - /usr/bin/yarn
 - npm: 7.7.6 - /usr/bin/npm
## npmPackages:
 - jest-puppeteer: ^6.0.0 => 6.0.0 
```

**Comment by vsDizzy** [comment]
Also please allow `.ts` and '.json' extensions for config file.
