### ISSUE TITLE
Negated version of `toMatchElement` does not take into account element visibility

### ISSUE THREAD

**Issue by 36degrees** [argos-ci/jest-puppeteer#459]
## 🐛 Bug Report

`expect(instance).toMatchElement(selector, {visible: true})` does not take into account element visibility as you'd expect it to.

## To Reproduce

Given a page with a hidden div containing the text 'Foo' (for example, `<div style="display: none;">Foo</div>`), a test with the following assertion should pass:

```js
expect(page).not.toMatchElement('div', { text: 'Foo', visible: true })
```

However, the test fails with:

```
Element div (text: "Foo") found
```

## Expected behavior

Based on [the documentation for the `toMatchElement` method](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/README.md#expectinstancetomatchelementselector-options) I'd expect setting `visible: true` to only consider elements that are visible – as such it should not match and the test should pass.

## Link to repl or repo (highly encouraged)

Adding this test to `packages/expect-puppeteer/src/matchers/notToMatchElement.test.js` demonstrates the issue:

```js
    it('should match taking into account visibility', async () => {
      const main = await page.$('main')
      await expect(main).not.toMatchElement('div', { text: 'displayed element', visible: true })
    })
```

It fails with:

```
  ● not.toMatchElement › ElementHandle › should match taking into account visibility

    TimeoutError: Element div (text: "displayed element") found
```

## Environment info

```bash
## System:
 - OS: macOS 11.6.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 436.18 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 7.24.2 - ~/.nvm/versions/node/v14.17.6/bin/npm
## npmPackages:
 - jest-puppeteer: ^5.0.4 => 5.0.4
```

(Having checked out the `main` branch of jest-puppeteer and added a test for the same functionality, I'm reasonably confident this issue is still present in 6.0.0 and above)

**Comment by gregberge** [comment]
Please upgrade to v8 and reopen submit a new issue if you experience this problem.
