### ISSUE TITLE
How to emulate devices with jest and puppeteer

### ISSUE THREAD

**Issue by bitstarr** [argos-ci/jest-puppeteer#510]
Since `puppeteer.devices()` got removed with puppeteer 19.1.0, there are no blog posts or other helping sources on how to emulate a certain device with a jest and puppeteer setup.

I'm not a JS or node expert, I'm new to jest and puppeteer, but I need to test my frontend.

So I got the following jest test:

```js
/**
 * @jest-environment puppeteer
 */

const { toMatchImageSnapshot } = require('jest-image-snapshot');
expect.extend({ toMatchImageSnapshot });

const puppet = require('puppeteer');
const iPhone = puppet.KnownDevices['iPhone X'];
const Tablet = puppet.KnownDevices['iPad portrait'];
// past three lines do just nothing and i don't know how to fix that

describe('Visual Regression Testing', () => {

    test('Home Page Tablet', async function(){
        await page.emulate( Tablet );
        await page.goto('http://example.com', {
            waitUntil: 'networkidle0',
        });

        const screenshot = await page.screenshot();
        expect(screenshot).toMatchImageSnapshot({
            failureThreshold: '0.10',
            failureThresholdType: 'percent',
        });
    });

});
```

these node packages are relevant, I guess:
```json
        "jest": "^29.3.1",
        "jest-image-snapshot": "^6.1.0",
        "jest-puppeteer": "^6.2.0",
        "puppeteer": "^19.5.0",
```

Does anyone have an idea how the code from the puppeteer docs
```js
import {KnownDevices} from 'puppeteer';
const iPhone = KnownDevices['iPhone 6'];
```
will transform to work with jest?

**Comment by gregberge** [comment]
Hello @bitstarr, I think you are looking for [`Page.emulate(device)`](https://pptr.dev/api/puppeteer.page.emulate).

**Comment by kajirikajiri** [comment]
The emulate function is calling setUserAgent and setViewport internally. It seems that both are not implemented and just throw an error.
https://github.com/puppeteer/puppeteer/blob/c356e8f8f54ce0d9f39e98f58be988c149ebcaa4/packages/puppeteer-core/src/api/Page.ts#L1286

I think pr is this.
https://github.com/puppeteer/puppeteer/pull/8989

Appears to be a response to webdriver-bidi.
https://w3c.github.io/webdriver-bidi/

playwright can use chrome. So we may be able to do it by copying playwright's implementation
