### ISSUE TITLE
Argument of type 'Request' is not assignable to parameter of type 'HTTPRequest'.   Type 'Request' is missing the following properties from type 'HTTPRequest': #private, client, continueRequestOverrides, responseForRequest, and 6 more.

### ISSUE THREAD

**Issue by justinfarrelldev** [argos-ci/jest-puppeteer#513]
## 🐛 Bug Report

There are two possible bugs that I have found which I believe are interconnected.

When I attempt to type a callback for a request, I get this error message:
```
Argument of type 'Request' is not assignable to parameter of type 'HTTPRequest'.   Type 'Request' is missing the following properties from type 'HTTPRequest': #private, client, continueRequestOverrides, responseForRequest, and 6 more.
```

 It appears that the types from `jest-environment-puppeteer/node_modules/@types/puppeteer` and `puppeteer` are out of sync in some way. 

Also, when executing the if statement `if (req.isInterceptResolutionHandled())...`, Typescript believes that `.isInterceptResolutionHandled` does not exist on the Request type, but it does seem to come in with that method (regardless of whether `Request` or `HTTPRequest` were used).

Puppeteer is on `^19.6.0` and jest-puppeteer is on `^6.2.0`.

## To Reproduce

Attempt to use `page.on('request')` with the HTTPRequest type provided from puppeteer. 
```typescript
import { HTTPRequest } from 'puppeteer';

// ...set up page...
page.on('request', async (req: HTTPRequest) => {
...
});
```

For the if statement, simply write out: 
```typescript
page.on('request', async (req) => {
  if (req.isInterceptResolutionHandled()) return null;
  ...
 }
```
The linter will show `Property 'isInterceptResolutionHandled' does not exist on type 'Request'.ts(2339)`
## Expected behavior

These types are equivalent and represent the types for Puppeteer.

EDIT: Reproduction repo: 
https://github.com/justinfarrelldev/jest-puppeteer-repro

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
*** Clipboard option removed - use clipboardy or clipboard-cli directly ***


## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
 - Memory: 2.69 GB / 7.57 GB
 - Container: Yes
 - Shell: 5.8.1 - /usr/bin/zsh
## Binaries:
 - Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
 - npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
## npmPackages:
 - jest-puppeteer: ^6.2.0 => 6.2.0 
```

**Comment by justinfarrelldev** [comment]
I added a reproduction repo here: https://github.com/justinfarrelldev/jest-puppeteer-repro

While making the reproduction repo, I noticed that if I tried to do it with `npm`, all seemed to go well. Is this maybe `yarn`-specific?

**Comment by gregberge** [comment]
Hi @justinfarrelldev, should be fixed in v8 since everything has been upgraded.
