### ISSUE TITLE
dist folder is missing on NPM release of jest-environment-puppeteer

### ISSUE THREAD

**Issue by codejunkienick** [argos-ci/jest-puppeteer#527]
I have this error on my e2e tests after upgrading to version 8. Apparently dist folder was not uploaded in latest release in jest-environment-puppeteer causing this error to appear  
`Error: Jest: Got error running globalSetup - /home/nick/**/globalSetup.js, reason: Cannot find module './dist/global-init'` 
![image](https://user-images.githubusercontent.com/13534654/223115620-fb8db6fa-2397-4902-b978-cdd42b778a26.png)

**Comment by gregberge** [comment]
Hi @codejunkienick, thanks, I published a new one. It should be fixed.
