### ISSUE TITLE
8.0.3 broken?  `Module jest-puppeteer should have "jest-preset.js" or "jest-preset.json" file at the root.`

### ISSUE THREAD

**Issue by fregante** [argos-ci/jest-puppeteer#532]
## 🐛 Bug Report

Jest refuses to run due to an error in the preset

```
● Validation Error:

  Module jest-puppeteer should have "jest-preset.js" or "jest-preset.json" file at the root.

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

## To Reproduce

```js
npm init -y
npm install --save-dev jest-puppeteer puppeteer jest
echo '{"preset":"jest-puppeteer"}' > jest.config.json
npx jest
```

## System:
 - OS: macOS 13.2.1
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 73.23 MB / 16.00 GB
 - Shell: 3.6.0 - /usr/local/bin/fish
## Binaries:
 - Node: 18.13.0 - /usr/local/bin/node
 - Yarn: 1.22.11 - /usr/local/bin/yarn
 - npm: 9.6.0 - /usr/local/bin/npm
## npmPackages:
 - jest-puppeteer: ^8.0.3 => 8.0.3

**Comment by fregante** [comment]
It worked, thanks! I'll probably report more issues later (I'm updating some deps in https://github.com/fregante/webext-dynamic-content-scripts/pull/56)

<img width="589" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/223697767-6f4086a1-cbf5-42ff-b873-af83f2ae8715.png">


<img width="418" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1402241/223697740-c8680fdb-bb0b-457e-b4f2-ba38a097a874.png">

**Comment by christjt** [comment]
@fregante I am also experiancing a bunch of chrome windows being sparned. Do you know any way to work around this?
