### ISSUE TITLE
Dependency Errors Using `npm i`

### ISSUE THREAD

**Issue by tmcconechy** [argos-ci/jest-puppeteer#542]
## 🐛 Bug Report

Getting dependency errors using `"jest-puppeteer": "8.0.5",`. Not sure i understand why because it says puppetteer 19 can be used.

## To Reproduce

- clone https://github.com/infor-design/enterprise-wc
- change package.json to
```
"jest-puppeteer": "8.0.5",
"puppeteer": "^19.7.3",
```
- run npm i
- see error

```
npm ERR! Found: jest-puppeteer@6.2.0
npm ERR! node_modules/jest-puppeteer
npm ERR!   dev jest-puppeteer@"8.0.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev jest-puppeteer@"8.0.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: puppeteer@19.7.3
npm ERR! node_modules/puppeteer
npm ERR!   peer puppeteer@">=19" from jest-puppeteer@8.0.5
npm ERR!   node_modules/jest-puppeteer
npm ERR!     dev jest-puppeteer@"8.0.5" from the root project
npm ERR!
```

## Expected behavior

Clean `npm i` without errors

## Link to repl or repo (highly encouraged)

[Please provide a minimal repository on GitHub.

https://github.com/infor-design/enterprise-wc

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 13.2.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 3.18 GB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 18.12.1 - ~/.nvm/versions/node/v18.12.0/bin/node
 - npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
## npmPackages:
 - jest-puppeteer: 8.0.5 => 6.2.0
```

**Comment by gregberge** [comment]
It is a problem about your dependencies, try to upgrade npm, remove package-lock.json, run npm upgrade. Anyway it is not relative to jest-puppeteer itself, so I close this issue.

**Comment by tmcconechy** [comment]
ok yeah your right @gregberge i tried this on a clean `npm` project and its fine. must be ours. sorry for the issue
