### ISSUE TITLE
Jest preset not working with latest jest and jest-puppeteer

### ISSUE THREAD

**Issue by Akxe** [argos-ci/jest-puppeteer#551]
## 🐛 Bug Report

command `jest` results in following error: 

```
TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')
  at new NodeEnvironment (node_modules/jest-environment-puppeteer/node_modules/jest-environment-node/build/index.js:86:49)
  at new PuppeteerEnvironment (node_modules/jest-environment-puppeteer/dist/index.js:225:1)
```

## To Reproduce

```javascript
var config = {
  projects: [
    {
      displayName: 'Node',
      browser: false,
      runner: 'jest-runner',
      testMatch: ['**/node.test.js'],
    },
    {
      displayName: 'Browser',
      runner: 'jest-runner',
      testMatch: ['**/browser.test.js'],
      preset: "jest-puppeteer",
    },
  ],
};

module.exports = config;
```

I tried using only `module.exports = { preset: "jest-puppeteer" }`, but got the same error...

To try it for yourself try cloning provided repo and run `npm i` and `npm run test`

## Expected behavior

Expecting this to work... it is on documentation and on README.

## Link to repl or repo (highly encouraged)

Repo: https://github.com/Akxe/gpmf-extract/tree/dev

## EnvInfo

```bash
## System:
 - OS: Windows 10 10.0.22621
 - CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
 - Memory: 16.83 GB / 31.89 GB
## Binaries:
 - Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
 - npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - jest-puppeteer: ^8.0.6 => 8.0.6
```

**Comment by jsfez** [comment]
Hello @Akxe, upgrade `jest` to the last version should fix your error.

**Comment by Akxe** [comment]
I did the update before writing the bug report. To no avail

**Comment by jsfez** [comment]
I've taken a look at your project and was able to reproduce the bug. After updating Jest to the latest version (29.5.0) using `npm install --save-dev jest@29.5.0`, the issue no longer persists.

Additionally, I came across an article ([link to the article](https://bobbyhadz.com/blog/jest-typeerror-cannot-read-properties-of-undefined-reading-testenvironmentoptions)) that may be of help in resolving similar issues. Please let us know if you need further assistance or if there's anything else we can do to help.

**Comment by Akxe** [comment]
I am sorry; I am certain I did update Jest at some point, but I must have accidentally reverted it.

Would you know what this error is?

```
Determining test suites to run...(node:94572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:94572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:94572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:94572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

You can update to the last `dev` branch or use the one with updated jest... Thanks!

**Comment by Akxe** [comment]
When I turned headless off, I saw that I am getting **23** instances of chromium for the duration of the test, yet I only have 4 active tests and 7 skipped (11 total)

![image](https://user-images.githubusercontent.com/2001798/233361368-51c3782c-7c6b-4155-b17f-7bf05a9de47d.png)

**Comment by gregberge** [comment]
Hello @Akxe, I am sorry but this issue become an "help thread". Your original issue was solved so I close it.
