### ISSUE TITLE
Snapshot serializers added with `expect.addSnapshotSerializer` are not used

### ISSUE THREAD

**Issue by askoufis** [argos-ci/jest-puppeteer#552]
## 🐛 Bug Report

Custom snapshot serializers added with [`expect.addSnapshotSerializer`](https://jestjs.io/docs/expect#expectaddsnapshotserializerserializer) are not used. Only custom snapshots serializers configured via [`snapshotSerializers`](https://jestjs.io/docs/configuration#snapshotserializers-arraystring) actually work.

This behaviour appears to have broken in version 8.

## To Reproduce

- `git clone https://github.com/askoufis/jest-puppeteer-repro`
- `pnpm install`
- `pnpm test`

The test in `foo.test.js` is run. This has a custom serializer added that prepends some text to the snapshot. However the snapshot does not contain this test, which is a bug.

- `git switch jest-puppeteer-7`
- `pnpm install`
- `pnpm test`

This branch has `jest-puppeter@7` installed. The snapshot serializer works in this case.

- `git switch config-snapshot-serializers`
- `pnpm install`
- `pnpm test`

This branch has the snapshot serializer configured in the jest config instead of the test file, and it's using `jest-puppeteer@8`. The snapshot now fails as the serializer has prepended some text to the snapshot, which is the expected behaviour.

## Expected behavior

Custom snapshot serializers added with `expect.addSnapshotSerializer` should work.

## Link to repl or repo (highly encouraged)

https://github.com/askoufis/jest-puppeteer-repro

## System info

Paste the results here:

```bash
## System:
 - OS: macOS 13.2.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 4.52 GB / 32.00 GB
 - Shell: 3.6.1 - /opt/homebrew/bin/fish
## Binaries:
 - Node: 16.20.0 - ~/.local/share/.volta/tools/image/node/16.20.0/bin/node
 - Yarn: 1.22.19 - ~/.local/share/.volta/tools/image/yarn/1.22.19/bin/yarn
 - npm: 8.19.4 - ~/.local/share/.volta/tools/image/node/16.20.0/bin/npm
 - Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
## npmPackages:
 - jest-puppeteer: ^8.0.6 => 8.0.6
```

**Comment by gregberge** [comment]
Hello @askoufis, thanks. I think it is a problem in the overriding of `expect`.

**Comment by askoufis** [comment]
Did a bit of debugging. To me, the overriding of `expect` is correct. It's fairly similar to the code in `expect-puppeteer` v7. What's interesting is that when calling `addSnapshotSerializer`, which is just an alias for [`addSerializer`](https://github.com/jestjs/jest/blob/299ab5c725575a302f0817806d31897cf793ac4d/packages/jest-snapshot/src/plugins.ts#L35), [the `PLUGINS` array](https://github.com/jestjs/jest/blob/299ab5c725575a302f0817806d31897cf793ac4d/packages/jest-snapshot/src/plugins.ts#L24) is updated correctly. However, when [`getSerializers`](https://github.com/jestjs/jest/blob/299ab5c725575a302f0817806d31897cf793ac4d/packages/jest-snapshot/src/plugins.ts#LL39C16-L39C16) is called later on (internally within jest somewhere), the `PLUGINS` array is back to its original state with only 7 elements (you'd expect there to be at least 8).

**Comment by askoufis** [comment]
Thanks for the fix! :)
