### ISSUE TITLE
Many browser windows open when running tests

### ISSUE THREAD

**Issue by YuriKopshev** [argos-ci/jest-puppeteer#554]
## 💥 Regression Report

A clear and concise description of what the regression is.

## Last working version

```
   "jest-puppeteer": "^6.2.0",
    "puppeteer": "^13.7.0"
```

Stopped working in version:

```
"jest-puppeteer": "^8.0.6",
 "puppeteer": "^20.2.1
```

## To Reproduce
Start tests by npm run test

## Expected behavior

Tests run in a single browser window

## Link to repl or repo (highly encouraged)

here is my repository with file package.json:

https://github.com/YuriKopshev/Jest_puppeteer_problem

Paste the results here:

**these are the messages I see on the command line when running tests, which opens a lot of browser windows:**

Determining test suites to run...(node:25296) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25296) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:25296) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:25296) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit

[screencast](https://monosnap.com/file/iF4gnMkIi7QTC0tGeYX0Ns72dfX7D4)

this doesn't happen with these versions:
```
 "jest-puppeteer": "^6.2.0",
   "puppeteer": "^13.7.0"
```

Please help me to solve this problem!

**Comment by tmilar** [comment]
this is the default and expected behavior, to be able to run multiple tests in parallel.

If you don't want or need it, you can use `--runInBand` option, which will instead run tests serially, opening only 1 window/tab at a time. This is also a good idea for low resource environments like CI.

**Comment by gregberge** [comment]
Hello @YuriKopshev, @tmilar is right, `--runInBand` is the correct way to run tests in the same browser. You can also adjust the number of tests running in parallel in Jest config.

**Comment by YuriKopshev** [comment]
Thanks guys for your answers. 
Yes, using the -i flag solves the issue. But if you look at my screencast attached to the question, then it seems to me that opening so many browsers for 3 tests does not look normal. At the same time, as I wrote above, there were no such problems in earlier versions of jest-puppeteer. 
**And the main problem is that you can’t find the right one among the huge number of tabs, where you can see how your tests are going! This is the main problem that caused me to ask the question.**

**Comment by tedmx** [comment]
That's a good highlight from Yuri and a valuable ticket.

I've spent a good deal of time understanding why the hell my jest-puppeteer launches dozens of Chrome windows, and that was with a very simple "Hello World" config, using the package in a very beginner-ish way.

Even if most users of the package are okay with that default behavior, I suggest adding a small note about it in README.
