### ISSUE TITLE
Using jest-puppeteer with nx

### ISSUE THREAD

**Issue by joaoschoen** [argos-ci/jest-puppeteer#562]
Hey there, I see that you guys use NX yourselves
I'm trying to integrate jest-puppeteer with my own project, I made a new node app using the nx generator, installed puppeteer, installed jest-puppeteer and set the jset.config.js file inside my app to have preset jest-puppeteer, but it's telling me "can't find name 'page'", the documentation tells me that I'd not need to import anything.
"There's no need to load any dependencies. Puppeteer's page and browser classes will automatically be exposed"

**Comment by gregberge** [comment]
Hello @joaoschoen, I am sorry I don't know what could cause this issue... It looks like there is a problem in your setup, maybe related to multiple jest projects?

**Comment by joaoschoen** [comment]
Perhaps, what I've done was basically:

Create an NX monorepository using create-nx-workspace
Use @nx/node to create a library
Edit the jest.config.js inside the lib to have it's preset be jest-puppeteer
Copy the Sample test from https://jestjs.io/docs/puppeteer

But when I run the test it get the mentioned error

**Comment by joaoschoen** [comment]
I changed some of my configs and now it works properly, and the "Cannot find name page" was fixed by using "global.page" instead of "page"

**Comment by joaoschoen** [comment]
/* eslint-disable */
export default {
  displayName: 'scraper',
  preset: 'jest-puppeteer',
  testEnvironment: "jest-environment-puppeteer",
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageDirectory: '../../coverage/libs/scraper',
};
here is the jest.config.ts file I'm using, in case someone comes here and has this problem
jest-environment-puppeteer is a lib you'll have to download
