### ISSUE TITLE
How can I launch jest-puppeteer with args?

### ISSUE THREAD

**Issue by itai-spiritt** [argos-ci/jest-puppeteer#563]
Hi all,

I'm facing the issue where I get the error 
`Running as root without --no-sandbox is not supported`
in my gitlab CI.

Reading here https://pptr.dev/troubleshooting/#running-puppeteer-on-gitlabci, I need to launch it with `{args: ['--no-sandbox', '--disable-setuid-sandbox']}`.
I couldn't find a way to set the jest preset with these args.

How can I do it? I don't want to opt out of the puppeteer preset.

thanks

**Comment by gregberge** [comment]
You can specify `args` in `launch` options: https://github.com/argos-ci/jest-puppeteer#synchronous-configuration
