### ISSUE TITLE
Missing license attribute in package.json?

### ISSUE THREAD

**Issue by bacall213** [argos-ci/jest-puppeteer#590]
## 💬 Questions and Help

Is there any particular reason the license attribute is not included in package.json? 

The jest-puppeteer github repo doesn't seem to include it in any of the versions I've checked back to v3, but the [npmjs mirror of jest-puppeteer v6.2.0](https://www.npmjs.com/package/jest-puppeteer/v/6.2.0?activeTab=code) appears to have included the license attribute.

When viewing the package on npmjs, license detection is failing to detect the MIT license in the license file so it's tagging the packages as having no license even though there is clearly a license. 

To view this another way, if you run: `npm view jest-puppeteer@6.2.0` you'll get something like this: `jest-puppeteer@6.2.0 | MIT | deps: 2 | versions: 61`

Checking the next version: `npm view jest-puppeteer@7.0.0` returns `jest-puppeteer@7.0.0 | Proprietary | deps: 2 | versions: 61`

All subsequent versions I've checked return the same Proprietary license tag even though the LICENSE file hasn't changed.

**Comment by gregberge** [comment]
Fixed in latest version.
